repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
    - id: terraform_fmt
      files: ^(.*/)?(terraform|tf-root)/.*\.tf$

    - id: terraform_tflint
      files: ^(terraform|tf-root)/.*\.tf$
    - id: terraform_validate
      files: ^(terraform|tf-root)/.*\.tf$
    - id: terraform_checkov
      files: ^(terraform|tf-root)/.*\.tf$
    - id: terraform_docs
      files: ^(terraform|tf-root)/.*\.tf$
      args:
        - '--args=--config=.terraform-docs.yml'

  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.4.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ['--baseline', '.secrets.baseline']
  #       exclude: terraform.tfstate
