name: K3S course Terraform Plan/Apply 

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-aws-region>

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: <terraform-version>

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Get Approval
        id: approval
        run: |
          echo "Approve or reject the Terraform changes."
          echo "::set-output name=approved::true" # Set to 'false' if rejected

      - name: Terraform Apply
        if: ${{ steps.approval.outputs.approved == 'true' }}
        run: terraform apply tfplan
